#!/bin/sh

IMAGE_NAME="xfrocks/acme.sh"
LATEST_VERSION="2.6.6"

docker build \
	--build-arg ACME_SH_VERSION="$LATEST_VERSION" \
	-t "$IMAGE_NAME" \
	-t "$IMAGE_NAME:$LATEST_VERSION" \
	.

docker push "$IMAGE_NAME" \
docker push "$IMAGE_NAME:$LATEST_VERSION"